# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: true

# Sidebar
sidebar: right
widgets:
- category
#- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  wenj: https://wenj.github.io/

# Miscellaneous
google_analytics: UA-119345306-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
# duoshuo_shortname: reqianduan
disqus_shortname: zhanghuimeng-blog

# Baidu share
baidushare: true